### ISSUE TITLE
Registration failed: no sender id provided

### ISSUE THREAD

**Issue by sahilyousif** [taromero/meteor-chrome-push-notifications#1] opened 2015-06-15 21:15 UTC
I created a ```manifest.json``` in the root directory and added the ```gcm_sender_id``` and ```gcm_user_visible_only``` keys. However I'm not sure how to get meteor to include this file while building (sorry, i'm new to meteor). Everytime I enable push notifications, the console shows up the error:
```Unable to subscribe to push. DOMException: Registration failed - no sender id provided```

I then tried including the manifest as such:
```<link rel="manifest" src="/manifest.json">```

Still no luck! Am i doing anything wrong here?

**Comment by taromero** [comment] 2015-06-15 22:12
Hi @sahilyousif thanks for pointing out the issue. I could reproduce it.

The problem occurs when trying to enable push notifications while **not** on the root path. This means that this will work on `localhost:3000/`, but not on `localhost:3000/mypath`. It seems like the library is trying to fetch the `manifest` file from a directory relative to the current path.

I will look at how to solve the problem, solving it today if it's simple enough.

**Comment by taromero** [comment] 2015-06-15 22:32
It seems like a problem with how Chrome's internal lib tries to fetch the `manifest.json` file. I don't know if I can work around it from this package.

I've posted a question on SO here: http://stackoverflow.com/questions/30856048/chrome-push-notifications-cant-subscribe-from-sub-path.

**Comment by sahilyousif** [comment] 2015-06-16 07:08
Hi @taromero. Thanks for the reply.

Actually I'm facing this issue even on a fresh project, where I am trying to enable push notifications from the root path itself. I tried using ```/manifest.json``` too, but still receive the error:

```Manifest parsing error: Line: 1, column: 1, Unexpected token.```
followed by
```Unable to subscribe to push. DOMException: Registration failed - no sender id provided```

When I check on dev tools if a ```manifest.json``` is actually received, and what are its contents - chrome has in fact received the application template instead of the manifest file, which is strange. ( on the browser ```http://localhost:3000/manifest.json``` opens up the application template and not the manifest.json)

Finally, I made a dummy project in Wamp, where i added service-worker.js in the root directory along with the manifest.json file with the gcm settings. In the html, I included
```<link rel="manifest" src="/manifest.json">```
and everything worked just fine! There was a popup asking me if I wanted to subscribe to Push Notifications and ...

Is it possible that this is an issue with meteor libraries?

**Comment by taromero** [comment] 2015-06-16 12:21
I think this might be an issue of where you are placing the `manifest.json` file.

It should be inside the `public` directory, that is the directory from where assets can be serve. Try moving the file to `public`, and it should work.

**Comment by taromero** [comment] 2015-06-16 12:51
So, to be clear, the problem you where having was because the `manifest.json` file wasn't placed inside the `public` directory.

The problem I described was unrelated, and caused by using `href="manifest.json"` instead of `href="/manifest.json"`.

Also note that Meteor currently doesn't handle 404 responses, it always response with an html, no matter the route.

Closing this, please reopen if needed.

**Closed by taromero** 2015-06-16 12:51 UTC

**Comment by sahilyousif** [comment] 2015-06-18 13:44
Yes it works perfectly now with the ```manifest.json``` in ```public``` directory. Thanks for the help.
